package com.example.demo.entity;

import java.util.Date;

import lombok.Data;

/**
 * ユーザー情報 Entity
 */
@Data
public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.name
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.address
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.phone
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.update_date
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.create_date
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.delete_date
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    private Date deleteDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.name
     *
     * @return the value of userinfo.name
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.name
     *
     * @param name the value for userinfo.name
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.address
     *
     * @return the value of userinfo.address
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.address
     *
     * @param address the value for userinfo.address
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.phone
     *
     * @return the value of userinfo.phone
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.phone
     *
     * @param phone the value for userinfo.phone
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.update_date
     *
     * @return the value of userinfo.update_date
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.update_date
     *
     * @param updateDate the value for userinfo.update_date
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.create_date
     *
     * @return the value of userinfo.create_date
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.create_date
     *
     * @param createDate the value for userinfo.create_date
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.delete_date
     *
     * @return the value of userinfo.delete_date
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public Date getDeleteDate() {
        return deleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.delete_date
     *
     * @param deleteDate the value for userinfo.delete_date
     *
     * @mbggenerated Thu Jul 27 20:12:14 JST 2023
     */
    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }
}